[phases.setup]
nixPkgs = ['python311', 'tesseract', 'playwright']

[phases.build]
cmds = [
  'pip install -r requirements.txt',
  'playwright install --with-deps'
]

[start]
cmd = 'cd VC_CRM && python main.py'